version: '3'

tasks:
  serve:
    desc: Serve the static site locally on port 8000
    cmds:
      - uv run python -m http.server 8000

  format:
    desc: Format code using Prettier
    cmds:
      - npx prettier --write "**/*.{html,css,js,json}"
